### ISSUE TITLE
Renovate leaves zombie processes running

### ISSUE THREAD

**Issue by alclonky** [whitesource/renovate-on-prem#110]
there are 230 git-remote-http zombie processes after running renovate for half a day
this can lead to PIDPressure on the host

**Comment by rarkins** [comment]
Can you provide more details?

**Comment by rarkins** [comment]
Tentative planning: use `dumb-init` as the `ENTRYPOINT`

**Comment by rarkins** [comment]
Fixed in v1.0.1
