### ISSUE TITLE
CocoaPods GitHub enterprise hosted dependency support

### ISSUE THREAD

**Issue by asoneji** [whitesource/renovate-on-prem#111]
We are currently using [renovate-on-prem](https://github.com/whitesource/renovate-on-prem) for our web app. We are looking to use the same in iOS, automate dependency updates for Cocoapods. We noticed an issue with GitHub enterprise hosted dependency (private Cocoapods repo) as they are not updated. Does renovate support CocoaPods GitHub enterprise hosted dependency? Any suggestion or fix for this issue?

**Comment by rarkins** [comment]
Cocoapods support is implemented within the [Renovate OSS repo](https://github.com/renovatebot/renovate) so once what you need is supported there then it can be added to the on prem solution too. Therefore please raise a feature request there with full details about environment, steps to reproduce, any relevant logs from today, etc.

**Comment by zpei0411** [comment]
Hi, @rarkins we use renovate-on-prem for a while, our team all appreciate it. Recently our ios team want to use renovate, but found the same issue happened like it https://github.com/renovatebot/renovate/issues/6568, not sure if have any plan or update for now? We are eager for it.

**Comment by rarkins** [comment]
The current status is https://github.com/renovatebot/renovate/issues/6568#issuecomment-789683770

I'm closing this here as we don't want to waste time tracking things twice like this.

**Comment by zpei0411** [comment]
Understand. But  [renovatebot/renovate#6568 (comment)](https://github.com/renovatebot/renovate/issues/6568#issuecomment-789683770) can not comment any more.

**Comment by rarkins** [comment]
Unlocked - that was an accident I think
