### ISSUE TITLE
Dashboard not detecting all Gitlab repositories under organization

### ISSUE THREAD

**Issue by altusgerona** [whitesource/renovate-on-prem#112]
Hi, am trying to install renovate on a private repository on a private organization in Gitlab. I can add renovate bot manually through the members tab but the dashboard can't see the project at all. Or any projects under that directory for that matter. So I can add the bot and it made the merge request that starts integration, but the webhook is still missing and it's still absent from the dashboard.

Do I need to do something for the dashboard to view all the repositories?

**Comment by rarkins** [comment]
> Hi, am trying to install renovate on a private repository

Do you mean the WhiteSource Renovate app? This is the repository for the on-premises version.

> on a private organization in Discord

Do you mean you work for Discord? Or does it mean something else?

> I can add renovate bot manually through the members tab

Do you mean https://gitlab.com/renovate-bot ?

> the webhook is still missing and it's still absent from the dashboard.

You can only view repositories in the dashboard if you have write permissions to the repo. You can only set up the webhook if you have admin permissions. Are both of those satisfied?

I recommend you try opening up developer tools in your browser when you load the dashboard to see if any URLs are failing.

**Comment by altusgerona** [comment]
Sorry, yes I do mean the WhiteSource Renovate app for Gitlab. Sorry, this was the link recommended by WhiteSource Support. Will try to create this issue in that link as well.

I not only have write permissions, I am an owner/admin of the org. 

I meant the webhook that renovate bot uses.

Looking at the url calls, it fails every other call with 404 but it still returns repositories from the crawl.
