### ISSUE TITLE
Document possible values of ACCEPT_WHITESOURCE_TOS

### ISSUE THREAD

**Issue by baurmatt** [whitesource/renovate-on-prem#113]
I've tried `true`, `'true'`, `yes` and `'yes'`. After looking in the code I realized that it needs to be set to `'y'`.

I couldn't find a good place to document this hence I'm just opening this issue.

**Comment by rarkins** [comment]
It's in the docs, but not the examples:

![image](https://user-images.githubusercontent.com/6311784/86917328-31b33400-c125-11ea-84fd-e2db79bdfa69.png)

**Comment by baurmatt** [comment]
haha :D This got merged just before I've opened this issue. Couldn't find it because I grepped through a local checkout which wasn't yet updated.

Thank you! :)
