### ISSUE TITLE
git-tags datasource could not create directory '/usr/sbin/.ssh'

### ISSUE THREAD

**Issue by etiennetremel** [whitesource/renovate-on-prem#121]
I'm experiencing the following ssh related error for git-tags datasource:

```
DEBUG: Datasource unknown error (repository=[redacted]])
       "datasource": "git-tags",
       "lookupName": "git@github.com:[redacted].git",
       "err": {
         "task": {
           "commands": [
             "ls-remote",
             "git@github.com:[redacted].git"
           ],
           "format": "utf-8"
         },
         "message": "Could not create directory '/usr/sbin/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: Could not create directory '/usr/sbin/.ssh'.\r\nHost key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

From the configuration I use, it is coming from the kustomize manager. I'm also using Terraform and the git repo referenced in the Terraform modules are correctly being processed.

The issue is definitely related to SSH and the simple-git package cannot find the key but I couldn't find the exact logic that could trigger such issue. I used the latest version v1.1.0-rc.0 which use `/usr/sbin` as home directory. 

I have the Github private key located at `/usr/src/app/renovate.private-key.pem` (as described in the [documentation](https://github.com/whitesource/renovate-on-prem/blob/9caa45424bc60706fead9fcb66ef1d25ed136df9/docs/configuration-github.md#configure-whitesource-renovate)).

I also tried using renovate cli in an isolated container and experienced similar error.

Any idea?

**Comment by rarkins** [comment]
Are you attempting to use SSH authentication for that repo?

**Comment by etiennetremel** [comment]
I do, I'm following this example from the unit tests of the kustomize manager: https://github.com/renovatebot/renovate/blob/master/lib/manager/kustomize/__fixtures__/depsInResources.yaml#L7

**Comment by rarkins** [comment]
Have you modified the default image at all, e.g. by ADD or COPY files in a Docker build or by mapping any additional files in using Volumes?

From what I can tell, it's attempting to fetch tags from a private github.com repo using git over SSH. There is no SSH key available, so it fails (and maybe the error messages are a bit confusing). Can you try using a https URL instead of git?

**Comment by etiennetremel** [comment]
Nothing was changed in the image, the private key is mounted at `/usr/src/app/renovate.private-key.pem` and a config which doesn't have anything related to SSH at `/usr/src/app/config.js`.

I switched configuration to use https in the kustomize base, from:
```
bases:
- git@github.com:kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
```
to
```
bases:
- github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6
```

Logs:
```
DEBUG: Datasource unknown error (repository=[redacted])
       "datasource": "git-tags",
       "lookupName": "github.com/[redacted]",
       "err": {
         "task": {
           "commands": ["ls-remote", "github.com/[redacted]"],
           "format": "utf-8"
         },
         "message": "fatal: 'github.com/[redacted]' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: fatal: 'github.com/[redacted]' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at GitExecutorChain.onFatalException (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/usr/src/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
       }
```

If I test with a terraform reference it does work:

```
module "test-module" {
  source = "git@github.com:kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6"
}
```


Can it be a bug in the kustomize manager, the lookup name seems to be different:

```
 "lookupName": "git@github.com:kubernetes-sigs/kustomize.git",
```

vs in terraform:
```
 "lookupName": "kubernetes-sigs/kustomize",
```

when using https in the base instead of git@:
```
"lookupName": "github.com/GrandVisionHQ/store-service",
```

**Comment by rarkins** [comment]
Does `https://github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6` work?

**Comment by etiennetremel** [comment]
yes, sorry I made it confusing.. I didn't want to add the source repo.. `https://github.com/kubernetes-sigs/kustomize//examples/multibases?ref=v1.0.6` was a random example

**Comment by etiennetremel** [comment]
Does renovate always use `/usr/src/app/renovate.private-key.pem` when interacting with git using SSH?

**Comment by rarkins** [comment]
> Does renovate always use `/usr/src/app/renovate.private-key.pem` when interacting with git using SSH?

No, that is not an SSH key, it's the way your app authenticates itself with GitHub.

Please reproduce the type of example you need in a public repo so that we can take a look. It doesn't appear to have anything specifically about WhiteSource Renovate On-Prem, i.e. would have the same behavior in the CLI too. In other words, please create a really simple example that reproduces the problem and be clear about any changes/"not real" modifications compared to your real use case.

**Comment by etiennetremel** [comment]
Hi Rarkins, apologize for the delay. 

> No, that is not an SSH key, it's the way your app authenticates itself with GitHub.

That totally make sense.


I had a better look at it and the problem is indeed coming from the kustomize manager which does not translate SSH based url into HTTPS causing Renovate to use SSH to communicate with the Github API using the git command. Since Renovate already use `GITHUB_TOKEN`, would it be fair to make the change in the Kustomize manager to correctly transform the package URL from SSH to HTTP?

I created a test repo [here](https://github.com/etiennetremel/renovate-kustomize-temp/pull/1) which contains both a `kustomization.yaml` and `main.tf` file. Both have the ssh git based url as source.

I executed Renovate and we can see that the lookup already fail during the onboard for the Kustomize file but not for the Terraform one.

As for testing, I'm using Docker with Renovate CLI (v23.47.2):

```
$ docker run -ti \
    -e GITHUB_TOKEN=$GITHUB_TOKEN \
    -v $PWD:/app \
    -v renovate.private-key.pem:/usr/src/app/renovate.private-key.pem \
    -w /app \
    node:14 bash
root@d03b97c8e859:/app# yarn start --log-level debug --token $GITHUB_TOKEN etiennetremel/renovate-kustomize-temp

[...]
DEBUG: Datasource unknown error (repository=etiennetremel/renovate-kustomize-temp)
       "datasource": "git-tags",
       "lookupName": "git@github.com:moredhel/remote-kustomize.git",
       "err": {
         "task": {
           "commands": ["ls-remote", "git@github.com:moredhel/remote-kustomize.git"],
           "format": "utf-8"
         },
         "message": "Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n",
         "stack": "Error: Host key verification failed.\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n\n    at GitExecutorChain.onFatalException (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)\n    at GitExecutorChain.<anonymous> (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)\n    at Generator.throw (<anonymous>)\n    at rejected (/app/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
       }
DEBUG: Failed to look up dependency git@github.com:moredhel/remote-kustomize.git (repository=etiennetremel/renovate-kustomize-temp, packageFile=kustomization.yaml, dependency=git@github.com:moredhel/remote-kustomize.git)
[...]
```

Since this issue is not related to the whitesource/renovate-on-prem repo, I will open an issue on the renovatebot/renovate project and link it from there.
