### ISSUE TITLE
Unable to use private maven registry

### ISSUE THREAD

**Issue by enricojonas** [whitesource/renovate-on-prem#125]
Hi,

I am trying to use private maven registry (Artifactory), but it's always failing. I have tried different approaches as the documentation is not 100% clear. This is my current config (the repo is maven central mirror + our own packages, it's working fine when used with maven):

```
 "packageRules": [
        {"managers": ["maven"], "registryUrls": ["https://artifactory.xxx.com/artifactory/xxx-maven-virtual/"] }
]

    "hostRules": [
        {
            "platform": "maven",
            "endpoint": "https://artifactory.xxx.com/artifactory/xxx-maven-virtual/",
            "username": "myuser",
            "encrypted": {"password": "myencryptedpassword"}
        }
    ]
```

but always ending up with this:

```
DEBUG: Looking up com.fasterxml.jackson.datatype:jackson-datatype-joda in repository https://artifactory.xxx.com/artifactory/xxx-maven-virtual/ (repository=xxx/xxx)
DEBUG: Dependency lookup unauthorized. Please add authentication with a hostRule (repository=xxx/xxx)
```

Do I miss anything? Something changed? I cannot find "endpoint" in the official docs for example but it's mentioned here:

https://github.com/renovatebot/config-help/issues/241

Thanks for your help,

//Enrico

**Comment by rarkins** [comment]
Please substitute `baseUrl` instead of `endpoint` in your `hostRules` and see [the documentation](https://docs.renovatebot.com/configuration-options/#hostrules) on `hostRules`. If any follow-up questions, please post them in the Config Help as these don't seem specific to the on-prem version.
