### ISSUE TITLE
encrypted password in hostRule does not seem to work

### ISSUE THREAD

**Issue by enricojonas** [whitesource/renovate-on-prem#126]
Hi,

I have now managed to get the dependency lookup towards artifactory working. This is what I have used:

```
packageRules": [
        {"managers": ["maven"], "registryUrls": ["https://artifactory.xxx.com/artifactory/xxx-maven-virtual"] }
]

    "hostRules": [
        {
            "hostType": "maven",
            "hostName": "artifactory.xxx.com",
            "username": "my-username",
            "password": "my-password"
        }
    ]
```

This is working.

However, when I try to use encrypted password like this:

```
packageRules": [
        {"managers": ["maven"], "registryUrls": ["https://artifactory.xxx.com/artifactory/xxx-maven-virtual"] }
]

    "hostRules": [
        {
            "hostType": "maven",
            "hostName": "artifactory.xxx.com",
            "username": "my-username",
            "encrypted": {"password": "encrypted-password"}
        }
    ]
```

It is not working. I am using this URL to encrypt the password: https://app.renovatebot.com/encrypt

Maybe this is not working for the on-prem version? How can it be done?

**Comment by rarkins** [comment]
This question is not related to WhiteSource Renovate On-Premises directly, please raise it in Config Help instead so we can discuss there.
