### ISSUE TITLE
Redis as a cache still viable?

### ISSUE THREAD

**Issue by krohrsb** [whitesource/renovate-on-prem#127]
Hello! I was curious if Redis as a cache for whitesource renovate on-prem was still viable? It is noted in the general "selfhosted" docs https://docs.renovatebot.com/self-hosted-configuration/#redisurl

I run this on kubernetes using statefulsets and some config magic to auto-distribute repos across numbered statefulset pods. I would like to share as much cache as possible.

**Comment by rarkins** [comment]
Yes, it is intended to be viable, although I have no visibility of who if anybody has been using it. There should be no difference in how it runs compared to the CLI so you can test it more simply that way first.

We use Redis as a cache in the hosted app but the way we bootstrap it is a little different compared to the CLI and WS Renovate On-Prem.

**Comment by krohrsb** [comment]
Seems WS Renovate On-Prem only initializes the cache package with

```
{ cacheDir: '/tmp/renovate/cache/renovate/' }
```

Despite adding `redisUrl` to the self-hosted config.

I believe the on-prem docker image's server.js would need to be updated to manage passing through the redisUrl to the config given to the cache init.

**Comment by rarkins** [comment]
Thanks for looking into it, I will see if we can resolve it

**Comment by mattegawel** [comment]
Hi, @rarkins, :heavy_plus_sign: for this issue. Storing cache in redis doesn't work for me also (I use renovate pro 1.1.0). Do you have any updates about fixing this issue?

**Comment by rarkins** [comment]
Should be now fixed in https://github.com/whitesource/renovate-on-prem/releases/tag/1.2.0
