### ISSUE TITLE
OnboardingConfig in config.js is not respected

### ISSUE THREAD

**Issue by rebeccatang16** [whitesource/renovate-on-prem#132]
Hi!

I have a config.js that specifies an onboardingConfig, but onboarding PRs are still being made with:
```
{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "extends": [
    "local>orgName/renovate-config"
  ]
}
``` 

The config.js looks like:
```
module.exports = {
  onboardingConfig: {
    extends: ["github>orgName/renovate-config"]
  },
  ...
};
```
It's mounted into the Kubernetes pod via a secret rather than a configmap because of some sensitive stuff we put in the rest of it. I can confirm from exec'ing into the pod that the config exists at `/usr/src/app/config.js` and appears to have the right contents.

Do you have any suggestions about why this is happening and how I can fix it?

**Comment by rarkins** [comment]
First of all, the on-prem code doesn't have any `onboardingConfig` logic in it. i.e. it doesn't set or manipulate it at any point intentionally. It really looks like you have somehow made a config error in your pod - I can't think of any other explanation for why Renovate would propose "github>orgName/renovate-config". Have you verified that it does this for *newly* onboarding repos too?

Final point, if you run the container with `LOG_LEVEL=debug` in env then the earliest logs when the container starts should include some debug information on the config detection and loading.

**Comment by rebeccatang16** [comment]
Yeah, I tested on a newly onboarding repo, and it made what I assume is the default onboardingConfig. This config.js worked when we had an NPM based config, by the way. (as in, `extends: ["@orgName"]`).

**Comment by rarkins** [comment]
I just realized that we have a feature where if Renovate is onboarding a repo e.g. `x/foo` then it looks for whether `x/renovate-config` exists and puts `local>x/foo` in the extends config. The logic is here: https://github.com/renovatebot/renovate/blob/e5ce9f7e5c44cddb7244e73c71b0e11610dd09df/lib/workers/repository/onboarding/branch/config.ts#L22-L24

Are you running this against github.com? i.e. `local>orgName/renovate-config` is the same as `github>orgName/renovate-config`?

If this is a problem then we might need to add a flag that lets you disable it. BTW I don't think this is specific to whitesource/renovate-on-prem

**Comment by wyardley** [comment]
> Are you running this against github.com? i.e. local>orgName/renovate-config is the same as github>orgName/renovate-config?

Yes, this exactly

**Comment by rebeccatang16** [comment]
> If this is a problem then we might need to add a flag that lets you disable it. BTW I don't think this is specific to whitesource/renovate-on-prem

Would it be better to move this discussion into an issue in the main repo?

**Comment by rarkins** [comment]
Yes, that would be best. What I think the status is:

- If you are onboarding repo `ORG/REPO`, and there exists `ORG/renovate-config`, then any configured onboarding config will be overridden to be `"extends": ["local>ORG/renovate-config"]`

Unfortunately I think the way GitHub works, if you simply rename that repo then Renovate will "follow" that redirect. You'd need to rename it, then create a new `ORG/renovate-config` over the top, and then delete the new one. I think doing so would stop the redirecting.

**Comment by wyardley** [comment]
We want / prefer the name to be the standard `renovate-config` - are you saying to avoid this behavior, we'd have to make a new one with a name that's not "renovate-config"?

**Comment by rarkins** [comment]
> We want / prefer the name to be the standard `renovate-config` - are you saying to avoid this behavior, we'd have to make a new one with a name that's not "renovate-config"?

Right now, if the repo exists with that name - or has been renamed as described above - then it will always onboarding with the `local>` prefix. So you'd need to rename it to something/anything else plus stop the redirect (either that or delete the repo and create a newly named one from scratch with same content)

> Also, not strongly opinionated with `local>` vs `github>` if either worked, but with our setup, the former doesn't actually seem to work.

I'm not aware of any reason why it shouldn't work. Can you check if the failure is onboarding-specific or if it also fails post-onboarding? e.g. create a repo with `renovate.json` manually using `local>` and see if that also fails.

**Comment by wyardley** [comment]
So, I'm wrong - turns out, `local>` does work fine for both onboarding and post-onboarding -- really sorry about that.

That said, we'll keep the other issue open, because we'd like to be able to use a consistent config, and `github>` IMO is easier to understand / follow than `local>` in this case.

It is odd, because before, when we were forcing the config with the `@orgname/renovate-config`, we also had an `orgname/renovate-config` GitHub repo (where the former came from), and overriding the onboarding config seemed to work for that case (unless the NPM version just takes precedence if it exists and can be found?)

**Comment by rarkins** [comment]
I think it's possible that your switching from npm to github-based presets coincided with this addition of this preset detection feature.

If you were to contribute a PR to the main repo which makes the autodetection optional then we'd accept it and it would flow downstream into this repo without anything specific needed here, so I'll close it out.
