### ISSUE TITLE
warning opened on many repos

### ISSUE THREAD

**Issue by Haroenv** [whitesource/renovate-on-prem#133]
https://github.com/algolia/instantsearch.js/issues/2863
https://github.com/algolia/doc-code-samples/issues/140
https://github.com/algolia/eslint-config-algolia/issues/85
https://github.com/algolia/react-instantsearch/issues/2860
https://github.com/algolia/search-insights.js/issues/179
https://github.com/algolia/places/issues/742

I'm not sure what this error means since all information is

> Error type: undefined. Note: this is a nested preset so please contact the preset author if you are unable to fix it yourself.

Thanks!

**Comment by rarkins** [comment]
Wrong repo, please see issues in the main renovate repo. It's an error and issues will be autoclosed on the next run

**Comment by Haroenv** [comment]
thanks for commenting, I didn't notice I opened it in the wrong place, sorry!
