### ISSUE TITLE
Can not name app "Renovate"

### ISSUE THREAD

**Issue by janpio** [whitesource/renovate-on-prem#138]
https://github.com/whitesource/renovate-on-prem/blob/master/docs/configuration-github.md says:
 
> Name the app "Renovate" so that it shows up as "renovate[bot]" in Pull Requests and can be recognized when GitHub sends webhooks.

This is not possible as a Renovate app already exists.

**Comment by rarkins** [comment]
Cc @janpio 

I double checked that webhook user detection isn't hardcoded and is built dynamically at runtime, so removed the mention of identifying webhooks from the naming text. You should be able to name it anything you want..
