### ISSUE TITLE
getInstallationRepositories returns a max of 100 for github enterprise

### ISSUE THREAD

**Issue by krohrsb** [whitesource/renovate-on-prem#146]
We use the autodiscover filter in order to scale our hosted solution.

I noticed some repos were never being processed by the scheduler and started to investigate.

It appeared that getInstallationRepositories would return a max of 100 entries (max page size).

I found https://github.com/renovatebot/renovate/issues/4140 but that did not solve the issue.

I then dug a bit more into the on-prem server logic and noticed that during the getInstallationRepositories phase, it does do pagination but in order to follow the link header, it does a regex match hard coded against the public github api `api.github.com`. Since we use an enterprise version we host ourselves, this would never match, and thus never paginate making us stuck at 100 entries (for the 1st page).

Would it be possible to make this regex for headers.link match dynamic? (in that it uses the configured github host).

I think one also needs to build the new url afterward to also include the custom host, otherwise it will default to api.github.com.

Let me know if you would like more detail.

Thanks.

**Comment by rarkins** [comment]
Thanks for reporting this. I just pushed whitesource/renovate:1.3.1 to Docker Hub. The only functional change should be this patch: https://github.com/whitesource/renovate-on-prem/releases/tag/1.3.1
