### ISSUE TITLE
Renovate 1.4.0 broken for gitlab?

### ISSUE THREAD

**Issue by alclonky** [whitesource/renovate-on-prem#151]
I updated to 1.4.0 and getting the following error (did not change config):

`
 INFO: Using cron schedule: * * * * *
 INFO: Job scheduler started
 INFO: Initialized GitLab webhook handler
 INFO: Server bound to port 8080
 INFO: jobScheduler running
ERROR: Unknown gitlabScheduler error
       "err": {
         "message": "Cannot read property 'link' of undefined",
         "stack": "TypeError: Cannot read property 'link' of undefined\n    at gitlabScheduler (/usr/src/app/src/server.js:1:12226)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
       },
       "message": "Cannot read property 'link' of undefined"
 INFO: jobScheduler running

`

**Comment by rarkins** [comment]
I've published 1.4.1 with a fix for the GitLab scheduler. Sorry for the trouble and thanks for reporting it.

**Comment by alclonky** [comment]
now I am getting
`
 INFO: Using cron schedule: * * * * *
 INFO: Job scheduler started
 INFO: Initialized GitLab webhook handler
 INFO: Server bound to port 8080
 INFO: jobScheduler running
 INFO: Discovered 195 repositories
 INFO: Applying autodiscoverFilter
 INFO: Repository list from scheduler
       "repos": ["repo"]
 INFO: Processing repository (repository=repo)
       "priority": 100,
       "reason": "scheduled"
ERROR: renovateRepository error (repository=repo)
       "err": {
         "message": "d is not a function",
         "stack": "TypeError: d is not a function\n    at N (/usr/src/app/src/server.js:1:37798)\n    at async e (/usr/src/app/src/server.js:1:38979)\n    at async startWorker (/usr/src/app/src/server.js:1:38614)"
       }

`

**Comment by rarkins** [comment]
Sorry, this is why I shouldn't release on a Friday. Please see 1.4.2
