### ISSUE TITLE
Can we have a new release to fix the scala dependencies issue?

### ISSUE THREAD

**Issue by snehal-kolte** [whitesource/renovate-on-prem#153]
We have scala based project and we need this https://github.com/renovatebot/renovate/pull/10306 
fix. 

It would be great if renovate the release as soon as possible. 
Thanks

**Comment by snehal-kolte** [comment]
cc @rarkins

**Comment by snehal-kolte** [comment]
@rarkins I was trying to raise PR but getting the permission issue. 
`remote: Permission to whitesource/renovate-on-prem.git denied to snehal-kolte.
fatal: unable to access 'https://github.com/whitesource/renovate-on-prem.git/': The requested URL returned error: 403
`

**Comment by rarkins** [comment]
The release will likely occur in around two weeks. Please hold tight until then. The PR is unnecessary because Renovate automation will update the references once the image is on Docker Hub.

**Comment by rarkins** [comment]
https://github.com/whitesource/renovate-on-prem/releases/tag/1.5.0
