### ISSUE TITLE
Latest tag on Docker Hub is not latest version

### ISSUE THREAD

**Issue by jezhodges** [whitesource/renovate-on-prem#157]
The `latest` tag assigned to the project is a old version of Renovate published over 1 year ago.

This caught me out whilst setting up so it might catch others out.

Can new release be tagged `latest` on push to Docker?

**Comment by rarkins** [comment]
I've removed the `latest` tag because it was unintentional and we don't want people to take releases blindly. Please use a tagged *version* and check release notes for each release before upgrading.
