### ISSUE TITLE
Update bundled NPM version

### ISSUE THREAD

**Issue by jftanner** [whitesource/renovate-on-prem#161]
A flexible `hostRules` configuration doesn't necessarily play nicely with versions of NPM prior to 7.11. See [this issue](https://github.com/renovatebot/renovate/issues/9941#issuecomment-901248922) for details as to why.

I've solved this locally by making a custom docker image which I then deploy instead.
Here's the Dockerfile, for those interested:
```Dockerfile
FROM whitesource/renovate:1.5.0

USER root
RUN npm i -g npm@7.20.x
```

But an updated bundled version would save some steps.
Even better, would be to make it customizable via an environment variable.

**Comment by rarkins** [comment]
I recommend you set `USER` back to non-root after you're done.

**Comment by rarkins** [comment]
We'll update npm to v7 in this distribution around the same time we do the same for the CLI Renovate images too.

If you're interested in dynamic npm versions (and dynamic other tools too) then you can map your Docker socket into the Renovate container and configure `binarySource=docker`. See https://github.com/renovatebot/docker-renovate#samples

**Comment by jftanner** [comment]
> I recommend you set USER back to non-root after you're done.

That's a good call, thanks.

>  you can map your Docker socket into the Renovate container

My bots and services run in Kuberenetes, so that's non-trivial. But I'll look into it further. Thank you.

**Comment by rarkins** [comment]
This may be helpful: https://github.com/renovatebot/helm-charts/tree/main/charts/renovate#docker-in-docker-configuration

**Comment by jftanner** [comment]
Ooh, stellar. I totally missed that. Thank you!
