### ISSUE TITLE
[Question] when will npm@8 be supported by default?

### ISSUE THREAD

**Issue by kerasing** [whitesource/renovate-on-prem#168]
Given that nodejs will be promoting 16 to LTS in less than two weeks, nodejs 16 includes npm 7 (which has a breaking change for the lockfile), and the 1.6.0 release from a few days ago was using nodejs14, when should we expect an update to on-prem that will be compatible with npm v7 by default? 

PS, there is a [major security release made days before to 1.6.0 that was also not included](https://nodejs.org/en/blog/vulnerability/oct-2021-security-releases/)

**Comment by rodoabad** [comment]
Thanks for the update @rarkins, we're also eagerly awaiting this update from Renovate as we're also having similar issues in our org.

**Comment by ajbowler** [comment]
Hi @rarkins, are there any updates on this? Node 16 has been LTS for a couple of weeks now.

**Comment by rarkins** [comment]
Unfortunately this will need to be delayed for weeks to months before we use it as default. In the meantime you can easily build you own:

```
❯ cat Dockerfile
FROM whitesource/renovate:1.6.2
USER 0
RUN install-tool node 16.13.0
USER 1000

❯ docker build . -t whitesource/renovate:node16

❯ docker run --rm whitesource/renovate:node16 node --version && npm --version
v16.13.0
8.1.3
```

**Comment by CubicNitrous** [comment]
> Unfortunately this will need to be delayed for weeks to months before we use it as default. In the meantime you can easily build you own:
> 
> ```
> ❯ cat Dockerfile
> FROM whitesource/renovate:1.6.2
> USER 0
> RUN install-tool node 16.13.0
> USER 1000
> 
> ❯ docker build . -t whitesource/renovate:node16
> 
> ❯ docker run --rm whitesource/renovate:node16 node --version && npm --version
> v16.13.0
> 8.1.3
> ```

@rarkins Is there any negative implication on projects using node < 16 by doing this?

**Comment by rarkins** [comment]
You can substitute node for npm in the above, and it will retain node 14. Just pick a valid npm version

**Comment by CubicNitrous** [comment]
> You can substitute node for npm in the above, and it will retain node 14. Just pick a valid npm version

Maybe i asked the wrong way.  Some of our developers are wanting me to run Renovate this way to support Node16 and Im wondering if there is any downstream impact to our other Renovate users.

**Comment by rarkins** [comment]
I haven't seen any node 16 vs 14 problems. But if you have npm@8 and get a Renovate PR against a repo which uses npm@6 then you'll see the lock file is "migrated" to the newer version in the process.

I am currently working on https://github.com/renovatebot/renovate/issues/11984 with npm aimed to be first, so you can follow that if you prefer to wait

**Comment by kerasing** [comment]
Do you have an estimate as to how long it will be part of LTS by default? The operations team that runs Renovate for my employer is hesitant to override the node version without understanding the implications within renovate itself.

**Comment by rarkins** [comment]
Please see https://github.com/whitesource/renovate-on-prem/releases/tag/2.0.0-pre.0. The new image ships with npm@8 but can dynamically downgrade to npm@6 when older lock files are found. Feedback welcome (including positive.. so that we can feel confident to release 2.0.0).

**Comment by kerasing** [comment]
@rarkins - do you have an estimate as to when 2.0 will be released as a non-pre-release?

**Comment by rarkins** [comment]
Once we have received sufficient feedback about the pre-release. Have you tested it?

**Comment by kerasing** [comment]
The operations team that runs our Renovate has declined to upgrade to the pre-release.
