### ISSUE TITLE
Renovate with local repository 

### ISSUE THREAD

**Issue by Ranganathbj** [whitesource/renovate-on-prem#179]
Hi, is this possible to test renovate in local machine on local repository?

I tried all possible ways to resolve the issue with integrating renovate in local machine to test code repo  in my local but no luck.

There is no supportive document or results in internet on this. Your official websites also don't have any information on this.

I got this requirement from my company to implement in local before we go with gitlab.

**Comment by rarkins** [comment]
No, there is not.
