### ISSUE TITLE
Creating a verified commit signing key for GitHub

### ISSUE THREAD

**Issue by natan-abolafya** [whitesource/renovate-on-prem#186]
Hi,

This question should possibly be asked to GitHub but maybe someone experienced could help me faster here.
Now that the `gitPrivateKey` setting is fixed, I'm struggling to get Verified commits on GitHub.

![image](https://user-images.githubusercontent.com/64091305/151807548-4e389bbc-13e0-4e8b-92be-da691db24f48.png)

[The documentation on GitHub](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-bots) for this is quite limited unfortunately. It implies it should just work out of the box but it doesn't.

I figured it could be that the key I generated does not match the commit information.
![image](https://user-images.githubusercontent.com/64091305/151808151-350284a7-3d4f-497f-bff7-9c349ade3c49.png)

I attempted to create a GPG key for username `renovate-appgate[bot]` and email `renovate-appgate[bot]@users.noreply.github.com` but gpg considers that e-mail invalid because of `[bot]`.
And now I'm out of ideas.

**Comment by rarkins** [comment]
It's not possible for an app to use GPG for commit signing. For this reason in the hosted app we use the email address of the "real" user `@renovate-bot` as the committer.

For this reason we're working on https://github.com/renovatebot/renovate/issues/11537 but hitting some speed bumps

**Comment by natan-abolafya** [comment]
I see, thanks.
so the `gitPrivateKey` is more intended for GitHub Enterprise and similar deployments then? Or I guess signed but Unverified is better than unsigned for some.

Is there any way that I can also apply the `@renovate-bot` workaround for this with one of our users?

**Comment by rarkins** [comment]
I can't promise it works, but you can try:
- Generate a GPG key and associate it with a "real" account
- Configure `gitAuthor` to have an email address matching that account
- Optionally configure `gitIgnoredAuthors` if you have any existing branches/commits you want to keep using (without it, Renovate will consider them "modified" and not update them)

**Comment by rarkins** [comment]
We can leave it open, thanks

**Comment by etiennetremel** [comment]
@natan-abolafya how did you manage to have the key imported, I'm using latest `whitesource/renovate:2.1.1` and Renovate fail to import the key, see below:

```
Command failed: gpg --import /tmp/git-private.key\ngpg: Fatal: can't create directory '/home/ubuntu/.gnupg': Permission denied
```

I'm referencing the key from an environment variable to `gitPrivateKey` in the `config.js`:
```
module.exports = {
  // ...
  gitPrivateKey: process.env.GIT_GPG_SIGNING_KEY,
  // ...
}
```

Am I missing something?

**Comment by natan-abolafya** [comment]
I pass it in the `RENOVATE_CONFIG=<json>` environment variable.

The failure doesn't look like related to that however. Perhaps a volume binding issue?

**Comment by konrad-ohms** [comment]
If you are using a config.js, you can also read a file from disk via Node.js.

```
const gitPrivateKey = require("fs").readFileSync("/usr/src/app/rbabuild-git-signing-key.pem").toString();

module.exports = {
...
    "gitPrivateKey": gitPrivateKey,
...
};
```

**Comment by etiennetremel** [comment]
I also tried using your method @konrad-ohms but no success:
```
Command failed: gpg --import /tmp/git-private.key
gpg: Fatal: can't create directory '/home/ubuntu/.gnupg': Permission denied

Error: gpg-failed
    at writePrivateKey (/usr/src/app/node_modules/renovate/dist/util/git/private-key.js:43:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async commitFiles (/usr/src/app/node_modules/renovate/dist/util/git/index.js:608:9)
    at async processBranch (/usr/src/app/node_modules/renovate/dist/workers/branch/index.js:339:27)
    at async writeUpdates (/usr/src/app/node_modules/renovate/dist/workers/repository/process/write.js:25:21)
    at async update (/usr/src/app/node_modules/renovate/dist/workers/repository/process/extract-update.js:108:15)
    at async Object.renovateRepository (/usr/src/app/node_modules/renovate/dist/workers/repository/index.js:40:21)
    at async q (/usr/src/app/src/server.js:1:44344)
    at async startWorker (/usr/src/app/src/server.js:1:45459)
```

@rarkins can it be that there is missing permission to allow Renovate to create the `~/.gnupg` directory in the Dockerfile?

**Comment by rarkins** [comment]
Doesn't seem to be:

```
❯ docker run  --rm -it whitesource/renovate:2.1.1 /bin/bash
ubuntu@9b9b22369a37:/usr/src/app$ cd ~
ubuntu@9b9b22369a37:~$ pwd
/home/ubuntu
ubuntu@9b9b22369a37:~$ mkdir .gpupg
ubuntu@9b9b22369a37:~$ ls -al
total 80
drwxrwxr-x 1 ubuntu root 4096 Feb  2 16:02 .
drwxr-xr-x 1 root   root 4096 Jan 17 09:15 ..
-rw-r--r-- 1 ubuntu root  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu root 3771 Feb 25  2020 .bashrc
drwxr-xr-x 4 ubuntu root 4096 Jan 17 09:19 .dotnet
drwxr-xr-x 2 ubuntu root 4096 Feb  2 16:02 .gpg
drwxr-xr-x 2 ubuntu root 4096 Feb  2 16:02 .gpupg
drwxr-xr-x 2 ubuntu root 4096 Jan 17 09:16 .gradle
drwxr-xr-x 2 ubuntu root 4096 Jan 17 09:16 .m2
drwxr-xr-x 3 ubuntu root 4096 Jan 17 09:17 .mix
drwxr-xr-x 1 ubuntu root 4096 Jan 17 09:15 .npm
drwxrwxr-x 4 ubuntu root 4096 Jan 17 09:15 .npm-global
-rw-rw-r-- 1 ubuntu root   36 Jan 17 09:15 .npmrc
-rw-r--r-- 1 ubuntu root  807 Feb 25  2020 .profile
drwxrwxr-x 1 ubuntu root 4096 Jan 17 09:16 bin
drwxrwxr-x 2 ubuntu root 4096 Jan 17 09:15 env.d
drwxr-xr-x 3 ubuntu root 4096 Jan 17 09:15 npm
drwxr-xr-x 3 ubuntu root 4096 Jan 17 09:15 yarn
ubuntu@9b9b22369a37:~$
```

**Comment by etiennetremel** [comment]
Thanks all, I managed to fix it by enforcing the user id/group to 1000 (ubuntu) in the Kubernetes pod security policy (which we need to get rid of since it's going to be removed in Kubernetes 1.25). If someone stumble upon this issue, this is what was changed:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
spec:
  // ...
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
```

**Comment by rarkins** [comment]
I think it might also be fine if group is 0

**Comment by natan-abolafya** [comment]
`platformCommit=true` fixes this, doesn' it?
