### ISSUE TITLE
Support for "Check this box to trigger a request for Renovate to run again on this repository" in renovate-on-prem

### ISSUE THREAD

**Issue by konrad-ohms** [whitesource/renovate-on-prem#187]
Hi,

on the public renovate GitHub bot there is an option on the dashboard "Check this box to trigger a request for Renovate to run again on this repository", e.g. https://github.com/renovatebot/.github/issues/8
![image](https://user-images.githubusercontent.com/40577406/152141437-73952b4c-652f-4c2e-854d-1303899bc8f2.png)

I really like that feature as I can trigger dependency updates explicitly, I tried to reproduce that behavior for renovate-on-prem by defining the following setting in my preset:

```
{
...
"dependencyDashboardFooter": "- [ ] Check this box to trigger a request for Renovate to run again on this repository",
...
}
```

This renders the checkbox, but if I check it, renovate seem to ignore the webhook.

This is the debug log when I check the checkbox:
```
{"name":"renovate","hostname":"95afb919741b","pid":8,"level":20,"logContext":"Y39D-lcrI","repository":"xxx","event":"issues","action":"edited","installationId":7172,"msg":"Received webhook event","time":"2022-02-02T11:02:50.189Z","v":0}
{"name":"renovate","hostname":"95afb919741b","pid":8,"level":20,"logContext":"Y39D-lcrI","repository":"xxx","msg":"Ignoring issue action: edited","time":"2022-02-02T11:02:50.189Z","v":0}
{"name":"renovate","hostname":"95afb919741b","pid":8,"level":20,"logContext":"Y39D-lcrI","repository":"xxx","event":"issues","action":"edited","installationId":7172,"msg":"Received webhook event","time":"2022-02-02T11:02:50.189Z","v":0}
{"name":"renovate","hostname":"95afb919741b","pid":8,"level":20,"logContext":"Y39D-lcrI","repository":"xxx","msg":"Ignoring issue action: edited","time":"2022-02-02T11:02:50.189Z","v":0}
```

I am running the docker image `whitesource/renovate:2.1.1` as a bot on GitHub Enterprise.

Is it possible to port that feature to renovate on-prem? I guess the GitHub app would need to be adjusted in order to not ignore that hook?

Thanks for any help

**Comment by rarkins** [comment]
See solution in #144
