### ISSUE TITLE
Please update to latest Renovate version

### ISSUE THREAD

**Issue by baurmatt** [whitesource/renovate-on-prem#203]
Hey,

once again I'd like to request a Renovate version update for renovate-on-prem. This time we're looking for the [`defaultRegistryUrls`](https://docs.renovatebot.com/configuration-options/#defaultregistryurls) feature. It was introduced with Renovate 31.62.0 -> https://github.com/renovatebot/renovate/commit/86b0ef09ae49db6a3b642c3f614bf1bb95fff690

Thanks in advance!

Regards,
Matthias

**Comment by Reamer** [comment]
I am also waiting for a new version, a colleague wrote a fix renovatebot/renovate#14212 which is included in 31.84.1.

**Comment by rarkins** [comment]
I'll aim to get a release out by end of next week

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/171657512-e1d6bb15-95d1-404a-8aae-0c6f96118d53.png)

The release in question above was already done^^
