### ISSUE TITLE
[Question] Is there any way to see more detailed information about self-host renovate running?

### ISSUE THREAD

**Issue by Xyz426** [whitesource/renovate-on-prem#206]
Hey, team 👋 , nice to meet you again :)

At present, the renovate of our self-host is installed by thousands of repo, and sometimes it is not updated at the `schedule` time specified by the repo. We hope to see some more detailed information. (e.g. which repository updates did renovate miss)

I found that Renovate has the [dashboard](https://app.renovatebot.com/dashboard), but the self-host renovate seems not to support it?

And I only found that self-host renovate has a `/status` API, that can see the current renovate running status. I can't find more official documents introducing other API interfaces, I want to know if there are other API interfaces that can be used?

**Comment by rarkins** [comment]
`/status` is about the only thing we have right now. If you can think of useful information to be added to it, please propose it.

Dashboards for self-hosted will hopefully be coming later this year

**Comment by m1n9o** [comment]
> `/status` is about the only thing we have right now. If you can think of useful information to be added to it, please propose it.
> 
> Dashboards for self-hosted will hopefully be coming later this year

Good to see such news, hope to see this feature!
