### ISSUE TITLE
PYTHONHOME was introduced in whitesource/renovate:2.3.1

### ISSUE THREAD

**Issue by m1n9o** [whitesource/renovate-on-prem#211]
May I ask why this environment variable `PYTHONHOME` [1] was introduced in the new version? From my understanding, it should not be configured in nearly all cases. 
The issue I encountered `[Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding](https://discuss.python.org/t/fatal-python-error-init-fs-encoding-failed-to-get-the-python-codec-of-the-filesystem-encoding/3173)` when I built our docker image based on whitesource/renovate:2.3.1 and tried to install `awscli`. Which is similar to [2].

Is there any suggestion?

[1] https://docs.python.org/3/using/cmdline.html#environment-variables
[2] https://discuss.python.org/t/fatal-python-error-init-fs-encoding-failed-to-get-the-python-codec-of-the-filesystem-encoding/3173

**Comment by rarkins** [comment]
It's not explicitly added by WS Renovate On-Prem. If it's from the image then it's included by buildpack, but it also has no explicit result for the variable: https://github.com/containerbase/buildpack/search?q=python_home
