### ISSUE TITLE
Ruby GEM paths missing from $PATH in 2.3.1

### ISSUE THREAD

**Issue by tigris** [whitesource/renovate-on-prem#214]
We upgraded from `2.3.0` to `2.4.0` recently and noticed all of our PRs for ruby projects started failing with an "Artifact update problem" - `/bin/sh: 1: bundler: not found`

After doing some digging, we found `bundle` used to be available in the path

```
#-❯ docker run --rm --platform linux/amd64 whitesource/renovate:2.4.0 bundle
[dumb-init] bundle: No such file or directory

#-❯ docker run --rm --platform linux/amd64 whitesource/renovate:2.3.1 bundle
[dumb-init] bundle: No such file or directory

#-❯ docker run --rm --platform linux/amd64 whitesource/renovate:2.3.0 bundle
Could not locate Gemfile
```

Digging around in the container, I can see the binary does indeed exist at `/usr/local/ruby/3.1.2/bin/bundle`, but perhaps the `PATH` is incorrect.

```
#-❯ docker run --rm --platform linux/amd64 whitesource/renovate:2.4.0 bash -c 'echo $PATH'
/go/bin:/home/ubuntu/.local/bin:/opt/buildpack/tools/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/go/bin:/home/ubuntu/.local/bin:/opt/buildpack/tools/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/home/ubuntu/.cargo/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

```
#-❯ docker run --rm --platform linux/amd64 whitesource/renovate:2.3.0 bash -c 'echo $PATH'
/usr/local/dotnet:/home/ubuntu/.gem-global/bin:/home/ubuntu/.gem/ruby/3.1.0/bin:/usr/local/ruby/3.1.2/bin:/home/ubuntu/.cargo/bin:/usr/local/rust/1.61.0/bin:/usr/local/go/1.18.3/bin:/go/bin:/usr/local/elixir/1.13.4/bin:/home/ubuntu/.local/bin:/usr/local/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/usr/local/gradle/7.4.2/bin:/home/ubuntu/bin:/usr/local/dotnet:/home/ubuntu/.gem-global/bin:/home/ubuntu/.gem/ruby/3.1.0/bin:/usr/local/ruby/3.1.2/bin:/home/ubuntu/.cargo/bin:/usr/local/rust/1.61.0/bin:/usr/local/go/1.18.3/bin:/go/bin:/usr/local/elixir/1.13.4/bin:/home/ubuntu/.local/bin:/usr/local/python/3.10.5/bin:/home/ubuntu/.npm-global/bin:/usr/local/gradle/7.4.2/bin:/home/ubuntu/bin:/home/ubuntu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

If the default PATH is configurable, I'm happy to update our config. I suspect this wasn't an intended change?

**Comment by rarkins** [comment]
Renovate should now be using binarySource=install and therefore dynamically installing Bundler at runtime. Please make sure you are running on latest (whitesource/renovate:2.4.0) and then run against a repo which needs a Gemfile.lock update. Please capture the debug logs for the branch in question (make sure you have LOG_LEVEL=debug set in env).

You should see an `install-tool bundler` command being run followed by the `bundler` command itself.

**Comment by rarkins** [comment]
Renovate should now be using binarySource=install and therefore dynamically installing Bundler at runtime. Please make sure you are running on latest (whitesource/renovate:2.4.0) and then run against a repo which needs a Gemfile.lock update. Please capture the debug logs for the branch in question (make sure you have LOG_LEVEL=debug set in env).

You should see an `install-tool bundler` command being run followed by the `bundler` command itself.

**Comment by tigris** [comment]
Thanks for the update @rarkins. We've updated our setup do use `binarySource=install` and will report back results after all the schedules run overnight.

Is there some docs about how to run with `binarySource=global`, e.g. we should update our setup to configure paths or something of we wanted to use that setting? I see the docs [here](https://docs.renovatebot.com/self-hosted-configuration/#binarysource) that `bundler` is not currently listed as supported for the `binarySource=install` option, but I will test further.

**Comment by rarkins** [comment]
It should already have binarySource=install as default. Please capture a log against a Ruby repo while running the latest version. I think the docs are out of date - will check

**Comment by forward2you** [comment]
After configuring binarySource=install, when scan ruby bundle repo, the matched bundler version will be installed under `/usr/local/bin/bundler`, with log 
```
Installing legacy tool bundler v2.3.17
Successfully installed bundler-2.3.17
1 gem installed
Bundler version 2.3.17
```
bundle is installed in `/usr/local/bin/bundler`
1. Does it means other repo using different bundle version will still update with bundler version 2.3.17?
2. We got another error `No /bin/bundler defined - aborting`, the debug log shows, how to debug this issue?
```
"err":{"errno":-2,"code":"ENOENT","syscall":"spawn /bin/sh","path":"/bin/sh","spawnargs":["-c","bundler lock --update"],"cmd":"bundler lock --update","stdout":"","stderr":"","message":"spawn /bin/sh ENOENT","stack":"Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"},"msg":"Gemfile.lock update failed due to an unknown reason","time":"2022-07-13T02:59:26.694Z","v":0}
```

**Comment by rarkins** [comment]
It will install whichever bundler version it needs every time

**Comment by tigris** [comment]
Thanks @rarkins. Previously we had `binarySource=global` in our custom config, rather than relying on the default. We've switched that over now as per your suggestion for use with `whitesource/renovate:2.4.0`. However we now get a different error, as shown below.

![Screen Shot 2022-07-13 at 5 21 39 pm](https://user-images.githubusercontent.com/26856/178674903-27528142-0789-4bd6-8b2e-27f08ad60de1.png)

The error from the logs is:

```json
{
  "err": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "spawn /bin/sh",
    "path": "/bin/sh",
    "spawnargs": [
      "-c",
      "bundler lock --update"
    ],
    "cmd": "bundler lock --update",
    "stdout": "",
    "stderr": "",
    "message": "spawn /bin/sh ENOENT",
    "stack": "Error: spawn /bin/sh ENOENT\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)\n    at onErrorNT (node:internal/child_process:478:16)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
  },
  "msg": "Gemfile.lock update failed due to an unknown reason",
  "time": "2022-07-13T02:59:26.694Z",
  "v": 0
}
```

We're trying `binarySource=docker` instead and getting some OK results so far, but quite confused as to what changed for `global` and `install` to stop working. I don't think we have anything custom in our setup, we're using the `whitesource/renovate:2.4.0` docker image as is.

**Comment by rarkins** [comment]
I've updated the buildpack version and explicitly installed Bundler into the image again. Can you run whitesource/renovate:2.4.1 without any custom binarySource config and tell me the result?
