### ISSUE TITLE
Remove tmp folder after Install poetry 

### ISSUE THREAD

**Issue by forward2you** [whitesource/renovate-on-prem#215]
We run renovate/renovate:2.4.0 image with BinarySource=docker configured.
It works well to upgrade bundler and npm.
When upgrading python poetry dependencies, it first start a renovate/python docker container, then run this command:

`docker run --rm --name=renovate_python --label=renovate_child --user=0:0 -v "/tmp/renovate/github/renovate-test/poetry-test":"/tmp/renovate/github/renovate-test/poetry-test" -v "/tmp/renovate/cache":"/tmp/renovate/cache" -w "/tmp/renovate/github/renovate-test/poetry-test" docker.io/renovate/python:3.10.5 bash -l -c "install-tool poetry 1.1.14 && poetry update --lock --no-interaction"`

Running `install-tool poetry 1.1.14` could successfully install poetry, but it failed at remove two temp folders that cannot be removed (the poetry-test is code repository)
```
Poetry version 1.1.14
Installed v1 poetry in 23 seconds
rm: cannot remove '/tmp/renovate/github/renovate-test/poetry-test': Device or resource busy
rm: cannot remove '/tmp/renovate/cache': Device or resource busy
```

My question is, does the rm folder a normal behavior? How could we avoid it?

**Comment by rarkins** [comment]
Should be fixed in 2.4.1
