### ISSUE TITLE
"Repository problems" continue to appear on the Dependency Dashboard

### ISSUE THREAD

**Issue by miyajan** [whitesource/renovate-on-prem#217]
"Repository problems" that were displayed on the Dependency Dashboard once in the past will continue to be displayed even after the problems are resolved.

As a workaround, after restarting Renovate On-Premises, the "Repository problems" disappear on the next Dependency Dashboard update.

**Comment by rarkins** [comment]
Can you capture and compare the logs from the repo for the two two runs where:
- issue is not updated 
- issue is updated as expected

**Comment by miyajan** [comment]
@rarkins 
Sorry, I have restarted Renovate On-premises, so I can't get the logs of when the problem was occurring. But no errors or warnings were logged in the Renovate On-premises logs when I checked during the problem was occurring with LOG_LEVEL=debug. I don't see anything significantly different in the logs before or after the restart.

The following screenshots were taken while the problem was occurring. The Dependency Dashboard was updated frequently, but "Repository problems" always remained. 

![スクリーンショット 2022-07-26 17 58 36](https://user-images.githubusercontent.com/945853/181140061-e51d477e-154b-4da6-9ace-de59ab5a9187.png)
![スクリーンショット 2022-07-26 17 58 48](https://user-images.githubusercontent.com/945853/181140076-a9809154-bfb3-4a59-9e6e-24838b5d4642.png)

- whitesource/renovate:2.3.1
- GitHub Enterprise Server: 3.5.2

Is it possible that Renovate stores Repository problems information in a global state and that this information has not been reset between runs?

**Comment by rarkins** [comment]
Yes, it's possible that there's a failure to clear out state. I'll look into it in depth in a couple of weeks once I'm back from vacation. Please ping me again here around then so I don't forget..

**Comment by miyajan** [comment]
@rarkins 
Is there any update on this?

**Comment by rarkins** [comment]
Should be fixed in https://github.com/whitesource/renovate-on-prem/releases/tag/2.5.0
