### ISSUE TITLE
feature: add opencontainers label to the whitesource/renovate docker image

### ISSUE THREAD

**Issue by mikaello** [whitesource/renovate-on-prem#229]
**What would you like Whitesource Renovate to be able to do?**

Make distributed docker image contain `org.opencontainers.image.source` label for easy reference back to this repository when [`whitesource/renovate`](https://hub.docker.com/layers/whitesource/renovate) image gets updates.

Currently there are no labels:

```shell
$ docker inspect whitesource/renovate:2.5.1 --format '{{ .Config.Labels }}'
map[]
```

Related issue in renovatebot: https://github.com/renovatebot/renovate/issues/3752

**Comment by rarkins** [comment]
This repo is not strictly the *source* of the image though, more like a "distribution" repo. Is your reason for Renovate itself, e.g. release notes, or for other tooling benefit?

**Comment by mikaello** [comment]
In our use case, the reason is for release notes.

We are building a custom image off of `whitesource/renovate`, and we are using Renovate to update the version of that base image. For those not familiar with the setup of Renovate it can require some searching to find the correct repository to see the release notes.

It is some other [pre-defined OCI keys](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys), but none of those seems like a perfect match (and Renovate currently only [supports `...revision` and `...source`](https://github.com/renovatebot/renovate/blob/075bf89e232416186c60bb7fb0c7f78dea5afc94/lib/modules/datasource/docker/common.ts)). Closest for this use case (of only fetching release notes) seems to be `org.opencontainers.image.url`, documented as *URL to find more information on the image (string)*.

**Comment by rarkins** [comment]
Sounds ok then, even if not strictly correct

**Comment by rarkins** [comment]
Added in https://github.com/whitesource/renovate-on-prem/releases/tag/2.5.2

**Comment by mikaello** [comment]
I notice that in the new versions of the docker image, the image source is now pointing to https://github.com/containerbase/base, is that intentional? I would have expected that this repo (github.com/mend/renovate-ce-ee) be the source.

```
$ docker inspect ghcr.io/mend/renovate-ce:6.2.0 --format '{{ json .Config.Labels }}' | jq
{
  "maintainer": "Rhys Arkins <rhys@arkins.net>",
  "org.opencontainers.image.ref.name": "ubuntu",
  "org.opencontainers.image.source": "https://github.com/containerbase/base",
  "org.opencontainers.image.version": "9.20.8"
}
```

**Comment by morremeyer** [comment]
@mikaello Check #365, this issue was raised there.
