### ISSUE TITLE
[Question] Is there any way to use dashboard on Renovate Pro?

### ISSUE THREAD

**Issue by miyajan** [whitesource/renovate-on-prem#58]
I am investigating Renovate Pro to use with GitHub Enterprise. It works well but there seems no dashboard like the one renovate on cloud provides.

https://renovatebot.com/dashboard

Is there any way to use the dashboard on Renovate Pro?

**Comment by rarkins** [comment]
This feature is not yet supported for self-hosted, but it is in planning. What aspect are you most interested in - is it the ability to automatically archive logs?

**Comment by miyajan** [comment]
Yes. Logs are very helpful for users when they are in trouble with renovate's configurations.

**Comment by enricojonas** [comment]
@rarkins I am trying to use dashboards with renovate on premises. It seems it works, is it fully supported?

I observed one issue where merged branches are still showing as open in the dashboard, so even if everything is up to date the dashboard will still show "These updates have all been created already. Click a checkbox below to force a retry/rebase of any.".

Is this is know issue? I can see it's still called master issue and not dependency dashboard as in the OSS version.

Thank you

**Comment by enricojonas** [comment]
@rarkins I saw there was a newer version available on docker hub, 1.1.0-rc.0. It seems that this is working much better and as expected when it comes to dependency dashboard functionality. Any plans when this will be released?

Thank you

**Comment by rarkins** [comment]
The dashboard sometimes still gets out of sync - it's not specific to this release. There are a few open issues in the OSS for improving it. 

If you're seeing Ignored warnings be sure to check your (debug) logs to see if Renovate does think that any previously-updated dependency needs updating again.

**Comment by wangyun1517** [comment]
> @rarkins I am trying to use dashboards with renovate on premises. It seems it works, is it fully supported?
> 
> I observed one issue where merged branches are still showing as open in the dashboard, so even if everything is up to date the dashboard will still show "These updates have all been created already. Click a checkbox below to force a retry/rebase of any.".
> 
> Is this is know issue? I can see it's still called master issue and not dependency dashboard as in the OSS version.
> 
> Thank you

What the link of the dashboard ?

**Comment by rarkins** [comment]
The above mention of "dashboard" is referring to the `dependencyDashboard` feature, which you can find in the docs. At this point there is no intention to port the hosted app's dashboard to WhiteSource Renovate On-Premises, so I'm closing this.
