### ISSUE TITLE
Issue configuring renovatePro with private NPM repositories.

### ISSUE THREAD

**Issue by moredhel** [whitesource/renovate-on-prem#98]
I have read a number of different issues relating to this & I still can't manage to get it configured correctly.

- https://github.com/renovatebot/renovate/issues/3551
- https://github.com/renovatebot/renovate/issues/851

## Config

```
RENOVATE_persistRepoData=true
RENOVATE_trustLevel=high
GITHUB_APP_ID=12345
LICENSE_NAME=MyCompany
RENOVATE_ENDPOINT=https://api.github.com/
RENOVATE_PLATFORM=github
SCHEDULER_CRON=*/2 06-19 * * 1-5
ACCEPT_AGREEMENT=y
LICENSE_MODE=commercial
RENOVATE_SECRET=<SECRET>
RENOVATE_npmToken=<NPM_TOKEN>
NPM_TOKEN=<NPM_TOKEN>
```

I have tried some combinations of these:
- only RENOVATE_npmToken
- NPM_TOKEN & trustLevel

I have pulled this information from the following:
https://docs.renovatebot.com/pro/configuration-github/

Thanks

**Comment by rarkins** [comment]
Are these private packages hosted by npmjs.org

**Comment by moredhel** [comment]
Yep, I should have clarified they are hosted by npmjs 

--

/moredhel

**Comment by rarkins** [comment]
Have you tried `RENOVATE_NPM_TOKEN`?

Also, set `LOG_LEVEL=debug` to get the maximum debugging at bootup time and check for when it prints out its config(s)

**Comment by moredhel** [comment]
Yep, I tried them both. I opted to use the config.js as the other options don't seem to be working.

This seems not to be working either:

Config:

```
DEBUG: Combined config
       "config": {
         "prFooter": "This PR was generated by [Renovate Bot](https://github.com/MyCompany/renovate-bot)",
         "trustLevel": "high",
         "logLevel": "debug",
         "npmToken": "***********",
         "hostRules": [
           {
             "hostType": "docker",
             "hostName": "https://mycompany.azurecr.io",
             "url": "https://mycompany.azurecr.io",
             "username": "",
             "password": ""
           }
         ],
         "platform": "github",
         "endpoint": "https://api.github.com/"
       }
```

the npmToken is populated as below _within the container_

```
module.exports = {
  ...,
  npmToken: process.env.NPM_TOKEN,
  ...
}
```

So it _should_ be passing through the env-var for injection into the repo-specific .npmrc file.

**Comment by rarkins** [comment]
> So it _should_ be passing through the env-var for injection into the repo-specific .npmrc file.

So your ultimate goal is to populate the `NPM_TOKEN` placeholder within an `.npmrc` file?

**Comment by moredhel** [comment]
My ultimate goal is to access private npm packages hosted on npmjs.

Above is an outline of what I have tried in order to achieve it
--

/moredhel

**Comment by rarkins** [comment]
Q1. Do your repos have `.npmrc` files already?
Q2. If so, can we ignore them or do they contain essential info we can’t replicate?

**Comment by moredhel** [comment]
A1. Yep, they all already have .npmrc files

A2. it’s completely safe to ignore them

**Comment by rarkins** [comment]
OK in that case we can attempt the approach of setting `ignoreNpmrc=true` and configuring all npmrc settings in the bot. e.g. like this:

```js
module.exports = {
  ignoreNpmrc: true,
  npmrc: '...................'
}
```

**Comment by moredhel** [comment]
Thanks, I’m currently testing this out. , I’ll get back to you if I am still struggling
